matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    nodejs:
    - 4
    - 6
    services:
    - docker
    before_install:
    - "./run_docker.sh"
    script:
    - make lint
    - make test
    - make e2e
  - os: linux
    dist: trusty
    sudo: required
    nodejs: 8
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_a2e08d5c220e_key -iv $encrypted_a2e08d5c220e_iv
      -in deploy.enc -out /tmp/deploy -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy
    - ssh-add /tmp/deploy
    services:
    - docker
    before_install:
    - "./run_docker.sh"
    script:
    - make lint
    - make test
    - make e2e
    deploy:
    - provider: script
      script: "./make_docs.sh"
      on:
        branch: master
        tags: true
    - provider: npm
      skip_cleanup: false
      email: webmakersteve@gmail.com
      api_key:
        secure: dCHdwKmSLmVU51eAiH/n7OT1WzyD2DZccjVt8luu6w7U61K3dnl26ZNcNqrRjglkCWj2mHwysYrlImNu/7DKoqNn6fJea6EFjESH9EjAgTbIFEbFyl1Bu+u9w68LEk8WKmCLQ4ckdXp4wm5A0G5+tn29Jg3+VBCy9OdZTFEw5Otwp5f/ARqv4vcnOQNNzdhpZX1o6M2i2zyzcjsKyrjUhuJIdtyXbc1H8aMXT4exRcTSTknbbV2pD4YN2mz5XOlORDLTap8q3W7UG5cPPvyd4Wsn6iiXcSlDJ5DZkQkx5DqJdzxE94pkS1WjDodW0TQtA55jj7qVhqwDwiQLHdClxQM4VN7wRDLoMsy811E9ockMwhgHXRjnQSlpRMux/ueqJnYzG7/zpKYokfJc2HoUv5Wx1Ae5nF//viUlYhEWI4E7cJatrnJnulmfJZOwQReOoInwNy7uVuzTVi0K9Q5X73e27nx5sp+gCcG3HiGQ07TB0hyqV0HWioKcYOqBUHnvMHkdMskPWC5mhTpiXcwk6JVdaUqqcwtqks1+9LiboOEYVb6CFIkmOAh/+mbOTDymTYbcKcdDJYFDOVJ8cMiCqIZ3J4gd/5+zTf2wTowYkBI/7t7Jq9X52tlRDmUn6vr6Zs4Ph+7qhpXHc3ov3p3g55s+ug968vDxogAxJt1NCUU=
      on:
        branch: master
        tags: true
  - os: osx
    osx_image: xcode8
    nodejs:
    - 4
    - 6
    script:
    - make lint
    - make test
    - make check
language: node_js
cache:
  directories:
  - node_modules
